export {
  create,
  createGlobalRegion,
  createRegionFromDefinition,
  extractETag,
  isEmptyGlobalRegion,
  extractGlobalRegions,
  getGlobalRegionsSettings,
  normalize,
  normalizeGlobalRegion,
  normalizeGlobalRegions,
  normalizeRegionDefinitions,
  resolve,
  resolveGlobalRegion,
  resolveGlobalRegionName,
} from "./globalRegions";
